name: test

on:
  push:
    branches:
      - main

env: 
  ENVIRONMENT: prd
  AWS_REGION: us-east-1

jobs: 
  test-build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read

    steps:

      - name: Checkout 
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done

      - name: Do BLAH build
        id: base_build
        if: ${{ contains(steps.files.outputs.all, 'docker/base/Dockerfile') }} 
        run: | 
          echo "docker/base/Dockerfile build!"

      - name: Do other build
        id: other_build
        run: | 
          echo "Always run this"
